import Image from "next/image";
import Navbar from "./components/landing-page/Navbar";
import LandingDisplay from "./components/landing-page/LandingDisplay";

export const metadata = {
  title: "CodingKita",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <LandingDisplay />
    
    </>
  );
}
