import React from 'react'
import LoginComp from '../components/login-page/login'

export const metadata = {
  title: "CK - Login",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <div><LoginComp /></div>
  )
}

export default LoginPage